// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB27VoE9EmuuslGG2I8mQBskfO3-H0RqJA',
    appId: '1:1075824828689:web:adb7328fdaca803a8cecb0',
    messagingSenderId: '1075824828689',
    projectId: 'finwise-81cd2',
    authDomain: 'finwise-81cd2.firebaseapp.com',
    storageBucket: 'finwise-81cd2.appspot.com',
    measurementId: 'G-Q8NY7Q7P6C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1MmYkEPJhxHIdQ32TJTlaDN4FMABrjzc',
    appId: '1:1075824828689:android:781f407a9b84f0b58cecb0',
    messagingSenderId: '1075824828689',
    projectId: 'finwise-81cd2',
    storageBucket: 'finwise-81cd2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLkHIGzO9Jo1N_PM-_Xr4AJUFqMYHqyL8',
    appId: '1:1075824828689:ios:72d06720f99733978cecb0',
    messagingSenderId: '1075824828689',
    projectId: 'finwise-81cd2',
    storageBucket: 'finwise-81cd2.appspot.com',
    iosBundleId: 'com.example.finwise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLkHIGzO9Jo1N_PM-_Xr4AJUFqMYHqyL8',
    appId: '1:1075824828689:ios:14186662ff464bbd8cecb0',
    messagingSenderId: '1075824828689',
    projectId: 'finwise-81cd2',
    storageBucket: 'finwise-81cd2.appspot.com',
    iosBundleId: 'com.example.finwise.RunnerTests',
  );
}
